version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing backend dependencies...
      - cd backend
      - npm install # Або команда для встановлення залежностей для backend

      - echo Installing frontend dependencies...
      - cd ../frontend
      - npm install # Або команда для встановлення залежностей для frontend
  build:
    commands:
      - echo Building backend...
      - cd ../backend
      - npm run build # Або команда для збирання backend

      - echo Building frontend...
      - cd ../frontend
      - npm run build # Або команда для збирання frontend

artifacts:
  files:
    - backend/build/**/* # Шлях до зібраного бекенду
    - frontend/build/**/* # Шлях до зібраного фронтенду
