version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing backend dependencies...
      - cd backend
      - mvn clean install

      - echo Installing frontend dependencies...
      - cd ../frontend
      - npm install
  build:
    commands:
      - echo Building backend...
      - cd ../backend
      - mvn clean package

      - echo Building frontend...
      - cd ../frontend
      - npm run build

artifacts:
  files:
    - backend/target/*.jar
    - frontend/build/**/*
