name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    name: Build Spring Boot Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build backend with Maven
        run: mvn -f backend/pom.xml clean package

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Build frontend
        run: npm run build --prefix frontend

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    needs: [build-backend, build-frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Replace the following deployment steps with your own deployment logic.
      # For example, if you're deploying to a server, you'll need to add steps to
      # copy the built files to the server and restart any services if necessary.
      - name: Deploy backend
        run: echo "Deploy backend to the server"

      - name: Deploy frontend
        run: echo "Deploy frontend to the server"
